theme: jekyll-theme-minimal
title: My First PR
description: Helping first time contributors to make their first contribution. My First PR.
logo: https://raw.githubusercontent.com/my-first-pr/my-first-pr.github.io/master/assets/images/logo.png
show_downloads: false